# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_plaintext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmscharfieldplugin',
            name='body',
            field=models.CharField(max_length=500, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='cmscharfieldplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_plaintext_cmscharfieldplugin', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='cmstextfieldplugin',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='cmstextfieldplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_plaintext_cmstextfieldplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
